### PR TITLE
Introducing the ability to export results to Amazon S3

### PR DESCRIPTION
**Pull request by InspectorGadget**
# Description

This PR introduces a new feature where Users could export their findings (From Service Screener) to an Amazon S3 Bucket with static website hosting enabled. This allows users to share the output with others without having to download the output.zip file and unzip it. However, it is a most useful feature for users who would like to keep their findings up-to-date.

**New features:**
- Ability to upload the output to a S3 bucket with static website hosting enabled
- Ability to generate a static website url for the output

**Motivation:**
This is a well anticipated feature (Me, personally too) and decided to contribute to the community.

## Type of change

Please delete options that are not relevant, and add any that may be relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Perform testing without the `bucket` parameter
  - Run the following command: `screener --region ap-southeast-1 --services iam`
    - Behavior: The output is generated as an output.zip file. You can [download the file](https://docs.aws.amazon.com/cloudshell/latest/userguide/working-with-cloudshell.html#files-storage) in the CloudShell console. Once downloaded, unzip the file and open 'index.html' in your browser. You should see a page like this:
- [x] Perform testing with the `bucket` parameter
  - Run the following command: `screener --region ap-southeast-1 --services iam --bucket {any-name}`
    - Behavior: The output is generated as an output.zip file. It is then uploaded to the S3 Bucket, and a static website url is generated in the CLI. You can open the url in your browser. 
    - You should see a page like this:
       Screenshot 2022-12-22 at 12 21 05 AM

**Test Configuration**:

- Firmware version: AWS CloudShell
- Hardware:
- Toolchain:
- SDK: AWS SDK (PHP)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have tested this change with all regions and services
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by InspectorGadget** [comment]
However, I am not sure if I placed the Uploader class in the right directory. I would appreciate if the right directory could be suggested.

**Comment by kuettai** [comment]
Hi @InspectorGadget , thank you for your initiative on creating PR. 

There are few changes required to be enhance before i proceed with the merge.

1. Service-Screener CLI accepted multiple regions as parameter. Hence need a better way to handle this (or maybe the first region in the parameter will be the region where the bucket will be created?). Also, try to test run with multiple regions in --region to test out
2. Need to provide IAM POLICY sample (least privileges) to create the public bucket in the README
3. Add try-catch when calling uploadZip, and shows proper error messages
4. No need to unzip, you can refers to line 125 in screen.php: "exec('cd adminlte; zip -r output.zip html; mv output.zip ../output.zip');"... whereas the raw html is actually in "adminlte"
5. Can we have a warning message when we receive *-b, or --bucket* parameter to warn customer that "**The report will be available through public internet, please ensure you understand the risk of exposing the report to the internet. You will be fully RESPONSIBLE on this data**". Then follow by request an input from user: "**Y**: Yes proceed, **N**: exit, **C**: Continue without creating the S3 bucket"
6. Can we move the /dashboard/uploader.php to /tools/uploader.class.php, as i plan to make a standard uploader class with different uploader driver in the future (e.g: S3, Azure Blob, SFTP server, custom endpoint?, dropbox?, workdoc?, gdoc?)

Feel free to reach out if any help needed.

**Comment by InspectorGadget** [comment]
Hey @kuettai,

Thank you for your detailed feedback on the implementation. I have went ahead and performed the necessary changes as below:

**PS**: I will be deleting the S3 Bucket below, as the PR rituals are done :P

---

> Service-Screener CLI accepted multiple regions as parameter. Hence need a better way to handle this (or maybe the first region in the parameter will be the region where the bucket will be created?). Also, try to test run with multiple regions in --region to test out

This has been addressed. Please refer to the test cases as below:

* Test case 1: Run the script with the default CLI arguments (But with 'y' as the input to the prompt)
```
[cloudshell-user@ip-10-2-40-12 aws-service-screener]$ screener --region ap-southeast-1 --services iam --bucket service-screener-raeveen
[info]  -- Acquiring identify info...
[info] Scanning iam
[info] ... (IAM::Account) inspecting
[info] NoSuchEntity
[info] ... (IAM::User) inspecting [redacted]
[info] #### (32) <iam> completed within 44.873s
[info] Total Resources scanned: 32 | No. Rules executed: 103
[info] Time consumed: 44.876
[info] iampageBuilder class not found, using default pageBuilder
[info] Pages generated, download output.zip to view
[info] CloudShell user, you may use this path: ~/service-screener/output.zip
[info] You have specified a 'bucket' parameter, the report will be uploaded to S3.
[info] The report will be available through public internet, please ensure you understand the risk of exposing the report to the internet. You will be fully RESPONSIBLE on this data.
Are you sure you want to continue? (y/n): y
[info] *** Uploading files to S3 bucket: service-screener-raeveen (region: ap-southeast-1)
[info] *** Upload completed ***
[info] You may visit the report at: http://service-screener-raeveen.s3-website-ap-southeast-1.amazonaws.com
[info] @ Thank you for using Service Screener @
```

* Test case 2: Run the script with the default CLI arguments (But with 'c' as the input to the prompt)
```
[cloudshell-user@ip-10-2-40-12 aws-service-screener]$ screener --region ap-southeast-1 --services iam --bucket service-screener-raeveen
[info]  -- Acquiring identify info...
[info] Scanning iam
[info] ... (IAM::Account) inspecting
[info] NoSuchEntity
[info] ... (IAM::User) inspecting [redacted]
[info] #### (32) <iam> completed within 44.842s
[info] Total Resources scanned: 32 | No. Rules executed: 103
[info] Time consumed: 44.845
[info] iampageBuilder class not found, using default pageBuilder
[info] Pages generated, download output.zip to view
[info] CloudShell user, you may use this path: ~/service-screener/output.zip
[info] You have specified a 'bucket' parameter, the report will be uploaded to S3.
[info] The report will be available through public internet, please ensure you understand the risk of exposing the report to the internet. You will be fully RESPONSIBLE on this data.
Are you sure you want to continue? (y/n): c
[info] You have chosen not to upload the report to S3. Continuing...
[info] @ Thank you for using Service Screener @
[cloudshell-user@ip-10-2-40-12 aws-service-screener]$ 
```

* Test case 3: Run the script with the default CLI arguments (But with 'n' as the input to the prompt)
```
[cloudshell-user@ip-10-2-40-12 aws-service-screener]$ screener --region ap-southeast-1,ap-southeast-2 --services iam --bucket service-screener-raeveen
[info]  -- Acquiring identify info...
[info] Scanning iam
[info] ... (IAM::Account) inspecting
[info] NoSuchEntity
[info] ... (IAM::User) inspecting [redacted]
[info] #### (32) <iam> completed within 43.943s
[info] Total Resources scanned: 32 | No. Rules executed: 103
[info] Time consumed: 43.946
[info] iampageBuilder class not found, using default pageBuilder
[info] Pages generated, download output.zip to view
[info] CloudShell user, you may use this path: ~/service-screener/output.zip
[info] You have specified a 'bucket' parameter, the report will be uploaded to S3.
[info] The report will be available through public internet, please ensure you understand the risk of exposing the report to the internet. You will be fully RESPONSIBLE on this data.
Are you sure you want to continue? (y/n): n
[info] You have chosen not to upload the report to S3.
[info] @ Thank you for using Service Screener @
[cloudshell-user@ip-10-2-40-12 aws-service-screener]$ 
```

---
> Need to provide IAM POLICY sample (least privileges) to create the public bucket in the README

This has been addressed. Please refer to the README.md file.

---
> Add try-catch when calling uploadZip, and shows proper error messages

This has been addressed. Please refer to the `uploader.class.php` file. There are some additional error handling that was added.

* Handle the case where the bucket name is already taken
* Handle the case where the bucket name is invalid
* Handle the case where creation of the S3 Bucket fails.

---
> No need to unzip, you can refers to line 125 in screen.php: "exec('cd adminlte; zip -r output.zip html; mv output.zip ../output.zip');"... whereas the raw html is actually in "adminlte"

Thanks man! I overlooked this. This has been addressed.

---
> Can we have a warning message when we receive -b, or --bucket parameter to warn customer that "The report will be available through public internet, please ensure you understand the risk of exposing the report to the internet. You will be fully RESPONSIBLE on this data". Then follow by request an input from user: "Y: Yes proceed, N: exit, C: Continue without creating the S3 bucket"

Yup! This has been addressed. More on the prompts can be found in `screen.php` file, line `133` onwards.

---
> Can we move the /dashboard/uploader.php to /tools/uploader.class.php, as i plan to make a standard uploader class with different uploader driver in the future (e.g: S3, Azure Blob, SFTP server, custom endpoint?, dropbox?, workdoc?, gdoc?)

Sounds good! The uploader class has been moved to the `tools` folder and renamed accordingly.

**Comment by kuettai** [comment]
README.md
- Example 1 will not works as it does not have sufficient permission to make the bucket as public website
- We just need the example 2, and combine all the different "SID" into one SID, e.g: '"Action": [s3:GetObject, s3:PutObject"...]'
- Instead of '"Resource": "*"', can we make the example more granular? E.g: "Resource": "arn:aws:s3:::<sample_bucket>/*" etc. Read more: https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-with-s3-actions.html

screen.php 
- Improve user experience through asking "y/n/c" at the beginning as soon as bucket flag detected. It is odd to get user to input again after waiting for 2-5minutes.
- stored "strtolower($confirm)" as directly as $confirm instead of multiple "strtolower" called.
- Need handling of input other than y/n/c, maybe a WHILE loop to prompt user to input again until they key in valid values.
- readline ("Are you sure you want to continue? (y/n):") should properly let user know there is another option to proceed without creating the bucket


Other than that, should be ok to merge.

**Comment by InspectorGadget** [comment]
Hey @kuettai ,

I have gone ahead and performed the suggested changes;

> README.md

The README now has consolidated IAM policy with the consolidated SIDs. 

> screen.php

A while loop has been introduced to ensure the user are entering a valid input (stdin). `strtolower()` is now used once, and at a strategic location. The user input prompt is now asked at the beginning of the script, right when the `bucket` parameter is found. 


Once again, I would like to thank you for your time in reviewing the changes, and also providing a descriptive feedback on how I could improve the implementation. 

Merry Christmas!

Cheers,
InspectorGadget

**Comment by kuettai** [comment]
screen.php
- For the while-loop check, use "do-while", https://www.w3schools.com/php/php_looping_do_while.asp, need proper handler to show "You have entered an invalid option".
- $bucketFlag is not being use anywhere in the code, remove it.
- $uploader->uploadFromFolder should return TRUE/FALSE flag, only only echo both "Upload completed and visit the report" message if it is TRUE.

Merry Belated Christmas!

**Comment by InspectorGadget** [comment]
Hey @kuettai ,

I have went ahead and reviewed `screen.php` file. Below are the details;

---
> For the while-loop check, use "do-while", https://www.w3schools.com/php/php_looping_do_while.asp, need proper handler to show "You have entered an invalid option".
Thanks. I was able to use do-while instead - Plus, I believe that it would be TC friendly than while-loops. 

> $bucketFlag is not being use anywhere in the code, remove it.
Removed. 

> $uploader->uploadFromFolder should return TRUE/FALSE flag, only only echo both "Upload completed and visit the report" message if it is TRUE.
`uploadFromFolder()` now returns boolean, and the additional messages such as "Upload completed..." would only be shown if it is true. 

---
Some logs on how it actually looks in the CLI, provided now that I used `__warn()` instead of `__info()`. - With this, it allows the Users (Me included) to identify that there is a `Warning` message with color, which provides good UX and it is obvious too. 
```
[cloudshell-user@ip-10-4-89-12 aws-service-screener]$ screener --region ap-southeast-1 --services iam --bucket service-screener-raeveen
[info] You have specified a 'bucket' parameter, the report will be uploaded to S3.
[info] The report will be available through public internet, please ensure you understand the risk of exposing the report to the internet. You will be fully RESPONSIBLE on this data.
Please enter 'y' for yes, 'n' for no, or 'c' to continue without uploading the report to S3 : s
[__!! WARNING !!__] You have entered an invalid option. Please try again.
Please enter 'y' for yes, 'n' for no, or 'c' to continue without uploading the report to S3 : y
[info]  -- Acquiring identify info...
[info] Scanning iam
```
Screenshot 2022-12-28 at 3 38 07 PM

Have a good day. Let me know how it works out.

**Comment by kuettai** [comment]
Approved & Merged.

**Review by kuettai — COMMENTED** [review]
Refers to conversation logs

**Pull request merged**
